CFLAGS   += -w -mhtm -DSTM -I$(STM)/ -I../lib
CPPFLAGS := $(CFLAGS)
LDFLAGS  += -L$(STM) -I$(STM)/ -I../lib
LIBS     += $(CPPFLAGS) -lpisces -lm -ltcmalloc -lrt -lpthread -mcpu=power8 -mtune=power8 -fpermissive -lboost_system

